/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FilterGroupsPanel: typeof import('./src/components/FilterGroupsPanel.vue')['default']
    ImageEditor: typeof import('./src/components/ImageEditor.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    LayersPanel: typeof import('./src/components/LayersPanel.vue')['default']
  }
}
